version: '3'
services:
  web-base:
    image: "web-base"
    build: .
    container_name: "web-base-01"
    restart: "always"
    ports:
      - "19000:19000"
    working_dir: "/app"
    volumes:
      - ./build/:/app/build/